version: '3.1'

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=localroot
      - POSTGRES_PASSWORD=localrootpass
      - POSTGRES_DB=app