version: '3.1'

services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=localroot
      - POSTGRES_PASSWORD=localrootpass
      - POSTGRES_DB=app


